/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApiVipConnectivityRequest
 */
export interface ApiVipConnectivityRequest {
    /**
     * URL address of the API.
     * @type {string}
     * @memberof ApiVipConnectivityRequest
     */
    url: string;
    /**
     * Whether to verify if the API VIP belongs to one of the interfaces (DEPRECATED).
     * @type {boolean}
     * @memberof ApiVipConnectivityRequest
     */
    verifyCidr?: boolean;
    /**
     * A CA certficate to be used when contacting the URL via https.
     * @type {string}
     * @memberof ApiVipConnectivityRequest
     */
    caCertificate?: string | null;
    /**
     * A string which will be used as Authorization Bearer token to fetch the ignition from ignition_endpoint_url.
     * @type {string}
     * @memberof ApiVipConnectivityRequest
     */
    ignitionEndpointToken?: string | null;
}
