/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum ArchitectureSupportLevelId {
    X8664ARCHITECTURE = 'X86_64_ARCHITECTURE',
    ARM64ARCHITECTURE = 'ARM64_ARCHITECTURE',
    PPC64LEARCHITECTURE = 'PPC64LE_ARCHITECTURE',
    S390XARCHITECTURE = 'S390X_ARCHITECTURE',
    MULTIARCHRELEASEIMAGE = 'MULTIARCH_RELEASE_IMAGE'
}

