/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterHostRequirements } from './cluster-host-requirements';
/**
 * 
 * @export
 * @interface ClusterHostRequirementsList
 */
export interface ClusterHostRequirementsList extends Array<ClusterHostRequirements> {
}
