/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClusterProgressInfo
 */
export interface ClusterProgressInfo {
    /**
     * 
     * @type {number}
     * @memberof ClusterProgressInfo
     */
    totalPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterProgressInfo
     */
    preparingForInstallationStagePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterProgressInfo
     */
    installingStagePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterProgressInfo
     */
    finalizingStagePercentage?: number;
}
