/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
import { OperatorHostRequirements } from './operator-host-requirements';
/**
 * 
 * @export
 * @interface ClusterHostRequirements
 */
export interface ClusterHostRequirements {
    /**
     * Unique identifier of the host the requirements relate to.
     * @type {string}
     * @memberof ClusterHostRequirements
     */
    hostId?: string;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof ClusterHostRequirements
     */
    total?: ClusterHostRequirementsDetails;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof ClusterHostRequirements
     */
    ocp?: ClusterHostRequirementsDetails;
    /**
     * Host requirements related to requested operators
     * @type {Array<OperatorHostRequirements>}
     * @memberof ClusterHostRequirements
     */
    operators?: Array<OperatorHostRequirements>;
}
