/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiVip } from './api-vip';
import { ClusterNetwork } from './cluster-network';
import { DiskEncryption } from './disk-encryption';
import { IgnitionEndpoint } from './ignition-endpoint';
import { IngressVip } from './ingress-vip';
import { MachineNetwork } from './machine-network';
import { OperatorCreateParams } from './operator-create-params';
import { Platform } from './platform';
import { ServiceNetwork } from './service-network';
/**
 * 
 * @export
 * @interface ClusterCreateParams
 */
export interface ClusterCreateParams {
    /**
     * Name of the OpenShift cluster.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    name: string;
    /**
     * Guaranteed availability of the installed cluster. 'Full' installs a Highly-Available cluster over multiple master nodes whereas 'None' installs a full cluster over one node. 
     * @type {string}
     * @memberof ClusterCreateParams
     */
    highAvailabilityMode?: ClusterCreateParamsHighAvailabilityModeEnum;
    /**
     * Version of the OpenShift cluster.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    openshiftVersion: string;
    /**
     * OpenShift release image URI.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    ocpReleaseImage?: string;
    /**
     * Base domain of the cluster. All DNS records must be sub-domains of this base and include the cluster name.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    baseDnsDomain?: string;
    /**
     * IP address block from which Pod IPs are allocated. This block must not overlap with existing physical networks. These IP addresses are used for the Pod network, and if you need to access the Pods from an external network, configure load balancers and routers to manage the traffic.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    clusterNetworkCidr?: string;
    /**
     * The subnet prefix length to assign to each individual node. For example, if clusterNetworkHostPrefix is set to 23, then each node is assigned a /23 subnet out of the given cidr (clusterNetworkCIDR), which allows for 510 (2^(32 - 23) - 2) pod IPs addresses. If you are required to provide access to nodes from an external network, configure load balancers and routers to manage the traffic.
     * @type {number}
     * @memberof ClusterCreateParams
     */
    clusterNetworkHostPrefix?: number;
    /**
     * The IP address pool to use for service IP addresses. You can enter only one IP address pool. If you need to access the services from an external network, configure load balancers and routers to manage the traffic.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    serviceNetworkCidr?: string;
    /**
     * (DEPRECATED) The virtual IP used to reach the OpenShift cluster's API.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    apiVip?: string;
    /**
     * The virtual IPs used to reach the OpenShift cluster's API. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
     * @type {Array<ApiVip>}
     * @memberof ClusterCreateParams
     */
    apiVips?: Array<ApiVip>;
    /**
     * (DEPRECATED) The virtual IP used for cluster ingress traffic.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    ingressVip?: string;
    /**
     * The virtual IPs used for cluster ingress traffic. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
     * @type {Array<IngressVip>}
     * @memberof ClusterCreateParams
     */
    ingressVips?: Array<IngressVip>;
    /**
     * The pull secret obtained from Red Hat OpenShift Cluster Manager at console.redhat.com/openshift/install/pull-secret.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    pullSecret: string;
    /**
     * SSH public key for debugging OpenShift nodes.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    sshPublicKey?: string;
    /**
     * Indicate if virtual IP DHCP allocation mode is enabled.
     * @type {boolean}
     * @memberof ClusterCreateParams
     */
    vipDhcpAllocation?: boolean | null;
    /**
     * A proxy URL to use for creating HTTP connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof ClusterCreateParams
     */
    httpProxy?: string | null;
    /**
     * A proxy URL to use for creating HTTPS connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof ClusterCreateParams
     */
    httpsProxy?: string | null;
    /**
     * An \"*\" or a comma-separated list of destination domain names, domains, IP addresses, or other network CIDRs to exclude from proxying.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    noProxy?: string | null;
    /**
     * Indicate if the networking is managed by the user.
     * @type {boolean}
     * @memberof ClusterCreateParams
     */
    userManagedNetworking?: boolean | null;
    /**
     * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    additionalNtpSource?: string | null;
    /**
     * List of OLM operators to be installed.
     * @type {Array<OperatorCreateParams>}
     * @memberof ClusterCreateParams
     */
    olmOperators?: Array<OperatorCreateParams>;
    /**
     * Enable/disable hyperthreading on master nodes, worker nodes, or all nodes.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    hyperthreading?: ClusterCreateParamsHyperthreadingEnum;
    /**
     * The desired network type used.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    networkType?: ClusterCreateParamsNetworkTypeEnum;
    /**
     * Schedule workloads on masters
     * @type {boolean}
     * @memberof ClusterCreateParams
     */
    schedulableMasters?: boolean;
    /**
     * Cluster networks that are associated with this cluster.
     * @type {Array<ClusterNetwork>}
     * @memberof ClusterCreateParams
     */
    clusterNetworks?: Array<ClusterNetwork> | null;
    /**
     * Service networks that are associated with this cluster.
     * @type {Array<ServiceNetwork>}
     * @memberof ClusterCreateParams
     */
    serviceNetworks?: Array<ServiceNetwork> | null;
    /**
     * Machine networks that are associated with this cluster.
     * @type {Array<MachineNetwork>}
     * @memberof ClusterCreateParams
     */
    machineNetworks?: Array<MachineNetwork> | null;
    /**
     * 
     * @type {Platform}
     * @memberof ClusterCreateParams
     */
    platform?: Platform;
    /**
     * The CPU architecture of the image (x86_64/arm64/etc).
     * @type {string}
     * @memberof ClusterCreateParams
     */
    cpuArchitecture?: ClusterCreateParamsCpuArchitectureEnum;
    /**
     * 
     * @type {DiskEncryption}
     * @memberof ClusterCreateParams
     */
    diskEncryption?: DiskEncryption;
    /**
     * 
     * @type {IgnitionEndpoint}
     * @memberof ClusterCreateParams
     */
    ignitionEndpoint?: IgnitionEndpoint;
    /**
     * A comma-separated list of tags that are associated to the cluster.
     * @type {string}
     * @memberof ClusterCreateParams
     */
    tags?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum ClusterCreateParamsHighAvailabilityModeEnum {
    Full = 'Full',
    None = 'None'
}
/**
    * @export
    * @enum {string}
    */
export enum ClusterCreateParamsHyperthreadingEnum {
    Masters = 'masters',
    Workers = 'workers',
    None = 'none',
    All = 'all'
}
/**
    * @export
    * @enum {string}
    */
export enum ClusterCreateParamsNetworkTypeEnum {
    OpenShiftSDN = 'OpenShiftSDN',
    OVNKubernetes = 'OVNKubernetes'
}
/**
    * @export
    * @enum {string}
    */
export enum ClusterCreateParamsCpuArchitectureEnum {
    X8664 = 'x86_64',
    Aarch64 = 'aarch64',
    Arm64 = 'arm64',
    Ppc64le = 'ppc64le',
    S390x = 's390x',
    Multi = 'multi'
}

