/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterNetwork } from './cluster-network';
import { ServiceNetwork } from './service-network';
/**
 * 
 * @export
 * @interface ClusterDefaultConfig
 */
export interface ClusterDefaultConfig {
    /**
     * 
     * @type {string}
     * @memberof ClusterDefaultConfig
     */
    clusterNetworkCidr?: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterDefaultConfig
     */
    clusterNetworkHostPrefix?: number;
    /**
     * 
     * @type {number}
     * @memberof ClusterDefaultConfig
     */
    inactiveDeletionHours?: number;
    /**
     * 
     * @type {string}
     * @memberof ClusterDefaultConfig
     */
    serviceNetworkCidr?: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterDefaultConfig
     */
    ntpSource?: string;
    /**
     * 
     * @type {Array<ClusterNetwork>}
     * @memberof ClusterDefaultConfig
     */
    clusterNetworksIpv4?: Array<ClusterNetwork>;
    /**
     * 
     * @type {Array<ClusterNetwork>}
     * @memberof ClusterDefaultConfig
     */
    clusterNetworksDualstack?: Array<ClusterNetwork>;
    /**
     * 
     * @type {Array<ServiceNetwork>}
     * @memberof ClusterDefaultConfig
     */
    serviceNetworksIpv4?: Array<ServiceNetwork>;
    /**
     * 
     * @type {Array<ServiceNetwork>}
     * @memberof ClusterDefaultConfig
     */
    serviceNetworksDualstack?: Array<ServiceNetwork>;
    /**
     * This provides a list of forbidden hostnames. If this list is empty or not present, this implies that the UI should fall back to a hard coded list.
     * @type {Array<string>}
     * @memberof ClusterDefaultConfig
     */
    forbiddenHostnames?: Array<string>;
}
