/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClusterHostRequirementsDetails
 */
export interface ClusterHostRequirementsDetails {
    /**
     * Required number of CPU cores
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    cpuCores?: number;
    /**
     * Required number of RAM in MiB
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    ramMib?: number;
    /**
     * Required disk size in GB
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    diskSizeGb?: number;
    /**
     * Required installation disk speed in ms
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    installationDiskSpeedThresholdMs?: number;
    /**
     * Maximum network average latency (RTT) at L3 for role.
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    networkLatencyThresholdMs?: number | null;
    /**
     * Maximum packet loss allowed at L3 for role.
     * @type {number}
     * @memberof ClusterHostRequirementsDetails
     */
    packetLossPercentage?: number | null;
    /**
     * Whether TPM module should be enabled in host's BIOS.
     * @type {boolean}
     * @memberof ClusterHostRequirementsDetails
     */
    tpmEnabledInBios?: boolean;
}
