/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConnectivityCheckNic } from './connectivity-check-nic';
/**
 * 
 * @export
 * @interface ConnectivityCheckHost
 */
export interface ConnectivityCheckHost {
    /**
     * 
     * @type {string}
     * @memberof ConnectivityCheckHost
     */
    hostId?: string;
    /**
     * 
     * @type {Array<ConnectivityCheckNic>}
     * @memberof ConnectivityCheckHost
     */
    nics?: Array<ConnectivityCheckNic>;
}
