/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConnectivityCheckNic
 */
export interface ConnectivityCheckNic {
    /**
     * 
     * @type {string}
     * @memberof ConnectivityCheckNic
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectivityCheckNic
     */
    mac?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectivityCheckNic
     */
    ipAddresses?: Array<string>;
}
