/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { L2Connectivity } from './l2-connectivity';
import { L3Connectivity } from './l3-connectivity';
/**
 * 
 * @export
 * @interface ConnectivityRemoteHost
 */
export interface ConnectivityRemoteHost {
    /**
     * 
     * @type {string}
     * @memberof ConnectivityRemoteHost
     */
    hostId?: string;
    /**
     * 
     * @type {Array<L2Connectivity>}
     * @memberof ConnectivityRemoteHost
     */
    l2Connectivity?: Array<L2Connectivity>;
    /**
     * 
     * @type {Array<L3Connectivity>}
     * @memberof ConnectivityRemoteHost
     */
    l3Connectivity?: Array<L3Connectivity>;
}
