/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContainerImageAvailabilityResult } from './container-image-availability-result';
/**
 * 
 * @export
 * @interface ContainerImageAvailability
 */
export interface ContainerImageAvailability {
    /**
     * A fully qualified image name (FQIN).
     * @type {string}
     * @memberof ContainerImageAvailability
     */
    name?: string;
    /**
     * Size of the image in bytes.
     * @type {number}
     * @memberof ContainerImageAvailability
     */
    sizeBytes?: number;
    /**
     * Seconds it took to pull the image.
     * @type {number}
     * @memberof ContainerImageAvailability
     */
    time?: number;
    /**
     * The rate of size/time in seconds MBps.
     * @type {number}
     * @memberof ContainerImageAvailability
     */
    downloadRate?: number;
    /**
     * 
     * @type {ContainerImageAvailabilityResult}
     * @memberof ContainerImageAvailability
     */
    result?: ContainerImageAvailabilityResult;
}
