/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ContainerImageAvailabilityRequest
 */
export interface ContainerImageAvailabilityRequest {
    /**
     * Positive number represents a timeout in seconds for a pull operation.
     * @type {number}
     * @memberof ContainerImageAvailabilityRequest
     */
    timeout?: number;
    /**
     * List of image names to be checked.
     * @type {Array<string>}
     * @memberof ContainerImageAvailabilityRequest
     */
    images: Array<string>;
}
