/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContainerImageAvailability } from './container-image-availability';
/**
 * 
 * @export
 * @interface ContainerImageAvailabilityResponse
 */
export interface ContainerImageAvailabilityResponse {
    /**
     * List of images that were checked.
     * @type {Array<ContainerImageAvailability>}
     * @memberof ContainerImageAvailabilityResponse
     */
    images: Array<ContainerImageAvailability>;
}
