/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Cpu
 */
export interface Cpu {
    /**
     * 
     * @type {number}
     * @memberof Cpu
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof Cpu
     */
    frequency?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Cpu
     */
    flags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Cpu
     */
    modelName?: string;
    /**
     * 
     * @type {string}
     * @memberof Cpu
     */
    architecture?: string;
}
