/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateManifestParams
 */
export interface CreateManifestParams {
    /**
     * The folder that contains the files. Manifests can be placed in 'manifests' or 'openshift' directories.
     * @type {string}
     * @memberof CreateManifestParams
     */
    folder?: CreateManifestParamsFolderEnum;
    /**
     * The name of the manifest to customize the installed OCP cluster.
     * @type {string}
     * @memberof CreateManifestParams
     */
    fileName: string;
    /**
     * base64 encoded manifest content.
     * @type {string}
     * @memberof CreateManifestParams
     */
    content: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateManifestParamsFolderEnum {
    Manifests = 'manifests',
    Openshift = 'openshift'
}

