/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DhcpAllocationRequest
 */
export interface DhcpAllocationRequest {
    /**
     * The network interface (NIC) to run the DHCP requests on.
     * @type {string}
     * @memberof DhcpAllocationRequest
     */
    _interface: string;
    /**
     * MAC address for the API virtual IP.
     * @type {string}
     * @memberof DhcpAllocationRequest
     */
    apiVipMac: string;
    /**
     * MAC address for the Ingress virtual IP.
     * @type {string}
     * @memberof DhcpAllocationRequest
     */
    ingressVipMac: string;
    /**
     * Contents of lease file to be used for API virtual IP.
     * @type {string}
     * @memberof DhcpAllocationRequest
     */
    apiVipLease?: string;
    /**
     * Contents of lease file to be used for for Ingress virtual IP.
     * @type {string}
     * @memberof DhcpAllocationRequest
     */
    ingressVipLease?: string;
}
