/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DiskEncryption
 */
export interface DiskEncryption {
    /**
     * Enable/disable disk encryption on master nodes, worker nodes, or all nodes.
     * @type {string}
     * @memberof DiskEncryption
     */
    enableOn?: DiskEncryptionEnableOnEnum;
    /**
     * The disk encryption mode to use.
     * @type {string}
     * @memberof DiskEncryption
     */
    mode?: DiskEncryptionModeEnum;
    /**
     * JSON-formatted string containing additional information regarding tang's configuration
     * @type {string}
     * @memberof DiskEncryption
     */
    tangServers?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum DiskEncryptionEnableOnEnum {
    None = 'none',
    All = 'all',
    Masters = 'masters',
    Workers = 'workers'
}
/**
    * @export
    * @enum {string}
    */
export enum DiskEncryptionModeEnum {
    Tpmv2 = 'tpmv2',
    Tang = 'tang'
}

