/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DiskInstallationEligibility } from './disk-installation-eligibility';
import { DriveType } from './drive-type';
import { IoPerf } from './io-perf';
/**
 * 
 * @export
 * @interface Disk
 */
export interface Disk {
    /**
     * Determine the disk's unique identifier which is the by-id field if it exists and fallback to the by-path field otherwise
     * @type {string}
     * @memberof Disk
     */
    id?: string;
    /**
     * 
     * @type {DriveType}
     * @memberof Disk
     */
    driveType?: DriveType;
    /**
     * 
     * @type {boolean}
     * @memberof Disk
     */
    hasUuid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    vendor?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    hctl?: string;
    /**
     * by-path is the shortest physical path to the device
     * @type {string}
     * @memberof Disk
     */
    byPath?: string;
    /**
     * by-id is the World Wide Number of the device which guaranteed to be unique for every storage device
     * @type {string}
     * @memberof Disk
     */
    byId?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    wwn?: string;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    serial?: string;
    /**
     * 
     * @type {number}
     * @memberof Disk
     */
    sizeBytes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Disk
     */
    bootable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Disk
     */
    removable?: boolean;
    /**
     * Whether the disk appears to be an installation media or not
     * @type {boolean}
     * @memberof Disk
     */
    isInstallationMedia?: boolean;
    /**
     * 
     * @type {DiskInstallationEligibility}
     * @memberof Disk
     */
    installationEligibility?: DiskInstallationEligibility;
    /**
     * 
     * @type {string}
     * @memberof Disk
     */
    smart?: string;
    /**
     * 
     * @type {IoPerf}
     * @memberof Disk
     */
    ioPerf?: IoPerf;
    /**
     * A comma-separated list of disk names that this disk belongs to
     * @type {string}
     * @memberof Disk
     */
    holders?: string;
}
