/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DiskSpeed } from './disk-speed';
/**
 * 
 * @export
 * @interface DiskInfo
 */
export interface DiskInfo {
    /**
     * 
     * @type {string}
     * @memberof DiskInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DiskInfo
     */
    path?: string;
    /**
     * 
     * @type {DiskSpeed}
     * @memberof DiskInfo
     */
    diskSpeed?: DiskSpeed;
}
