/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DiskSpeedCheckRequest
 */
export interface DiskSpeedCheckRequest {
    /**
     * --filename argument for fio (expects a file or a block device path).
     * @type {string}
     * @memberof DiskSpeedCheckRequest
     */
    path: string;
}
