/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DiskSpeedCheckResponse
 */
export interface DiskSpeedCheckResponse {
    /**
     * The 99th percentile of fdatasync durations in milliseconds.
     * @type {number}
     * @memberof DiskSpeedCheckResponse
     */
    ioSyncDuration?: number;
    /**
     * The device path.
     * @type {string}
     * @memberof DiskSpeedCheckResponse
     */
    path?: string;
}
