/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DiskRole } from './disk-role';
/**
 * 
 * @export
 * @interface DiskConfigParams
 */
export interface DiskConfigParams {
    /**
     * 
     * @type {string}
     * @memberof DiskConfigParams
     */
    id: string;
    /**
     * 
     * @type {DiskRole}
     * @memberof DiskConfigParams
     */
    role?: DiskRole;
}
