/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainResolutionResponseResolutions } from './domain-resolution-response-resolutions';
/**
 * 
 * @export
 * @interface DomainResolutionResponse
 */
export interface DomainResolutionResponse {
    /**
     * 
     * @type {Array<DomainResolutionResponseResolutions>}
     * @memberof DomainResolutionResponse
     */
    resolutions: Array<DomainResolutionResponseResolutions>;
}
