/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainResolutionResponseResolutions
 */
export interface DomainResolutionResponseResolutions {
    /**
     * The domain that was resolved
     * @type {string}
     * @memberof DomainResolutionResponseResolutions
     */
    domainName: string;
    /**
     * The IPv4 addresses of the domain, empty if none
     * @type {Array<string>}
     * @memberof DomainResolutionResponseResolutions
     */
    ipv4Addresses?: Array<string>;
    /**
     * The IPv6 addresses of the domain, empty if none
     * @type {Array<string>}
     * @memberof DomainResolutionResponseResolutions
     */
    ipv6Addresses?: Array<string>;
}
