/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Information sent to the agent for downloading artifacts to boot a host into discovery.
 * @export
 * @interface DownloadBootArtifactsRequest
 */
export interface DownloadBootArtifactsRequest {
    /**
     * URL address to download the kernel.
     * @type {string}
     * @memberof DownloadBootArtifactsRequest
     */
    kernelUrl: string;
    /**
     * URL address to download the rootfs.
     * @type {string}
     * @memberof DownloadBootArtifactsRequest
     */
    rootfsUrl: string;
    /**
     * URL address to download the initrd.
     * @type {string}
     * @memberof DownloadBootArtifactsRequest
     */
    initrdUrl: string;
    /**
     * The base directory on the host that contains the /boot folder. The host will download boot artifacts into a folder in this directory.
     * @type {string}
     * @memberof DownloadBootArtifactsRequest
     */
    hostFsMountDir: string;
}
