/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * Event Name.
     * @type {string}
     * @memberof Event
     */
    name?: string;
    /**
     * Unique identifier of the cluster this event relates to.
     * @type {string}
     * @memberof Event
     */
    clusterId?: string | null;
    /**
     * Unique identifier of the host this event relates to.
     * @type {string}
     * @memberof Event
     */
    hostId?: string | null;
    /**
     * Unique identifier of the infra-env this event relates to.
     * @type {string}
     * @memberof Event
     */
    infraEnvId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    severity: EventSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    category?: EventCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    eventTime: Date;
    /**
     * Unique identifier of the request that caused this event to occur.
     * @type {string}
     * @memberof Event
     */
    requestId?: string;
    /**
     * Additional properties for the event in JSON format.
     * @type {string}
     * @memberof Event
     */
    props?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EventSeverityEnum {
    Info = 'info',
    Warning = 'warning',
    Error = 'error',
    Critical = 'critical'
}
/**
    * @export
    * @enum {string}
    */
export enum EventCategoryEnum {
    User = 'user',
    Metrics = 'metrics'
}

