/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeaturesupportlevelFeatures } from './featuresupportlevel-features';
/**
 * (DEPRECATED) List of features attached to openshift version
 * @export
 * @interface FeatureSupportLevel
 */
export interface FeatureSupportLevel {
    /**
     * Version of the OpenShift cluster.
     * @type {string}
     * @memberof FeatureSupportLevel
     */
    openshiftVersion?: string;
    /**
     * 
     * @type {Array<FeaturesupportlevelFeatures>}
     * @memberof FeatureSupportLevel
     */
    features?: Array<FeaturesupportlevelFeatures>;
}
