/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupportLevel } from './support-level';
/**
 * 
 * @export
 * @interface FeaturesupportlevelFeatures
 */
export interface FeaturesupportlevelFeatures {
    /**
     * (DEPRECATED) The ID of the feature
     * @type {string}
     * @memberof FeaturesupportlevelFeatures
     */
    featureId: FeaturesupportlevelFeaturesFeatureIdEnum;
    /**
     * 
     * @type {SupportLevel}
     * @memberof FeaturesupportlevelFeatures
     */
    supportLevel: SupportLevel;
}

/**
    * @export
    * @enum {string}
    */
export enum FeaturesupportlevelFeaturesFeatureIdEnum {
    ADDITIONALNTPSOURCE = 'ADDITIONAL_NTP_SOURCE',
    REQUESTEDHOSTNAME = 'REQUESTED_HOSTNAME',
    PROXY = 'PROXY',
    SNO = 'SNO',
    DAY2HOSTS = 'DAY2_HOSTS',
    VIPAUTOALLOC = 'VIP_AUTO_ALLOC',
    DISKSELECTION = 'DISK_SELECTION',
    OVNNETWORKTYPE = 'OVN_NETWORK_TYPE',
    SDNNETWORKTYPE = 'SDN_NETWORK_TYPE',
    PLATFORMSELECTION = 'PLATFORM_SELECTION',
    SCHEDULABLEMASTERS = 'SCHEDULABLE_MASTERS',
    AUTOASSIGNROLE = 'AUTO_ASSIGN_ROLE',
    CUSTOMMANIFEST = 'CUSTOM_MANIFEST',
    DISKENCRYPTION = 'DISK_ENCRYPTION',
    CLUSTERMANAGEDNETWORKINGWITHVMS = 'CLUSTER_MANAGED_NETWORKING_WITH_VMS',
    ARM64ARCHITECTURE = 'ARM64_ARCHITECTURE',
    ARM64ARCHITECTUREWITHCLUSTERMANAGEDNETWORKING = 'ARM64_ARCHITECTURE_WITH_CLUSTER_MANAGED_NETWORKING',
    PPC64LEARCHITECTURE = 'PPC64LE_ARCHITECTURE',
    S390XARCHITECTURE = 'S390X_ARCHITECTURE',
    SINGLENODEEXPANSION = 'SINGLE_NODE_EXPANSION',
    LVM = 'LVM',
    DUALSTACKNETWORKING = 'DUAL_STACK_NETWORKING',
    MULTIARCHRELEASEIMAGE = 'MULTIARCH_RELEASE_IMAGE',
    NUTANIXINTEGRATION = 'NUTANIX_INTEGRATION',
    DUALSTACKVIPS = 'DUAL_STACK_VIPS',
    USERMANAGEDNETWORKINGWITHMULTINODE = 'USER_MANAGED_NETWORKING_WITH_MULTI_NODE'
}

