/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum FeatureSupportLevelId {
    SNO = 'SNO',
    VIPAUTOALLOC = 'VIP_AUTO_ALLOC',
    CUSTOMMANIFEST = 'CUSTOM_MANIFEST',
    SINGLENODEEXPANSION = 'SINGLE_NODE_EXPANSION',
    LVM = 'LVM',
    ODF = 'ODF',
    CNV = 'CNV',
    NUTANIXINTEGRATION = 'NUTANIX_INTEGRATION',
    VSPHEREINTEGRATION = 'VSPHERE_INTEGRATION',
    DUALSTACKVIPS = 'DUAL_STACK_VIPS',
    CLUSTERMANAGEDNETWORKING = 'CLUSTER_MANAGED_NETWORKING',
    USERMANAGEDNETWORKING = 'USER_MANAGED_NETWORKING',
    MINIMALISO = 'MINIMAL_ISO'
}

