/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeatureSupportLevel } from './feature-support-level';
/**
 * (DEPRECATED) List of objects that containing a list of feature-support level and attached to openshift-version
 * @export
 * @interface FeatureSupportLevels
 */
export interface FeatureSupportLevels extends Array<FeatureSupportLevel> {
}
