/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Gpu
 */
export interface Gpu {
    /**
     * The name of the device vendor (for example \"Intel Corporation\")
     * @type {string}
     * @memberof Gpu
     */
    vendor?: string;
    /**
     * ID of the vendor (for example \"8086\")
     * @type {string}
     * @memberof Gpu
     */
    vendorId?: string;
    /**
     * ID of the device (for example \"3ea0\")
     * @type {string}
     * @memberof Gpu
     */
    deviceId?: string;
    /**
     * Product name of the device (for example \"UHD Graphics 620 (Whiskey Lake)\")
     * @type {string}
     * @memberof Gpu
     */
    name?: string;
    /**
     * Device address (for example \"0000:00:02.0\")
     * @type {string}
     * @memberof Gpu
     */
    address?: string;
}
