/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostStage } from './host-stage';
/**
 * 
 * @export
 * @interface HostProgressInfo
 */
export interface HostProgressInfo {
    /**
     * 
     * @type {number}
     * @memberof HostProgressInfo
     */
    installationPercentage?: number;
    /**
     * 
     * @type {HostStage}
     * @memberof HostProgressInfo
     */
    currentStage?: HostStage;
    /**
     * 
     * @type {string}
     * @memberof HostProgressInfo
     */
    progressInfo?: string;
    /**
     * Time at which the current progress stage started.
     * @type {Date}
     * @memberof HostProgressInfo
     */
    stageStartedAt?: Date;
    /**
     * Time at which the current progress stage was last updated.
     * @type {Date}
     * @memberof HostProgressInfo
     */
    stageUpdatedAt?: Date;
}
