/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MacInterfaceMap } from './mac-interface-map';
/**
 * 
 * @export
 * @interface HostStaticNetworkConfig
 */
export interface HostStaticNetworkConfig {
    /**
     * yaml string that can be processed by nmstate
     * @type {string}
     * @memberof HostStaticNetworkConfig
     */
    networkYaml?: string;
    /**
     * 
     * @type {MacInterfaceMap}
     * @memberof HostStaticNetworkConfig
     */
    macInterfaceMap?: MacInterfaceMap;
}
