/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
/**
 * 
 * @export
 * @interface HostTypeHardwareRequirements
 */
export interface HostTypeHardwareRequirements {
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof HostTypeHardwareRequirements
     */
    quantitative?: ClusterHostRequirementsDetails;
    /**
     * Host requirements that cannot be quantified at the time of calculation. Descriptions or formulas of requiements
     * @type {Array<string>}
     * @memberof HostTypeHardwareRequirements
     */
    qualitative?: Array<string>;
}
