/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Host } from './host';
import { HostProgressInfo } from './host-progress-info';
import { HostRegistrationResponseNextStepRunnerCommand } from './host-registration-response-next-step-runner-command';
import { HostRole } from './host-role';
import { HostStage } from './host-stage';
import { LogsState } from './logs-state';
/**
 * 
 * @export
 * @interface HostRegistrationResponse
 */
export interface HostRegistrationResponse extends Host {
    /**
     * 
     * @type {HostRegistrationResponseNextStepRunnerCommand}
     * @memberof HostRegistrationResponse
     */
    nextStepRunnerCommand?: HostRegistrationResponseNextStepRunnerCommand;
}


