/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Command for starting the next step runner
 * @export
 * @interface HostRegistrationResponseNextStepRunnerCommand
 */
export interface HostRegistrationResponseNextStepRunnerCommand {
    /**
     * 
     * @type {string}
     * @memberof HostRegistrationResponseNextStepRunnerCommand
     */
    command?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HostRegistrationResponseNextStepRunnerCommand
     */
    args?: Array<string>;
    /**
     * How long in seconds to wait before retrying registration if the command fails
     * @type {number}
     * @memberof HostRegistrationResponseNextStepRunnerCommand
     */
    retrySeconds?: number;
}
