/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DiskConfigParams } from './disk-config-params';
import { DiskSkipFormattingParams } from './disk-skip-formatting-params';
import { NodeLabelParams } from './node-label-params';
/**
 * 
 * @export
 * @interface HostUpdateParams
 */
export interface HostUpdateParams {
    /**
     * 
     * @type {string}
     * @memberof HostUpdateParams
     */
    hostRole?: HostUpdateParamsHostRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof HostUpdateParams
     */
    hostName?: string | null;
    /**
     * 
     * @type {Array<DiskConfigParams>}
     * @memberof HostUpdateParams
     */
    disksSelectedConfig?: Array<DiskConfigParams> | null;
    /**
     * Allows changing the host's skip_formatting_disks parameter
     * @type {Array<DiskSkipFormattingParams>}
     * @memberof HostUpdateParams
     */
    disksSkipFormatting?: Array<DiskSkipFormattingParams> | null;
    /**
     * 
     * @type {string}
     * @memberof HostUpdateParams
     */
    machineConfigPoolName?: string | null;
    /**
     * A string which will be used as Authorization Bearer token to fetch the ignition from ignition_endpoint_url.
     * @type {string}
     * @memberof HostUpdateParams
     */
    ignitionEndpointToken?: string | null;
    /**
     * Labels to be added to the corresponding node.
     * @type {Array<NodeLabelParams>}
     * @memberof HostUpdateParams
     */
    nodeLabels?: Array<NodeLabelParams> | null;
}

/**
    * @export
    * @enum {string}
    */
export enum HostUpdateParamsHostRoleEnum {
    AutoAssign = 'auto-assign',
    Master = 'master',
    Worker = 'worker'
}

