/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Explicit ignition endpoint overrides the default ignition endpoint.
 * @export
 * @interface IgnitionEndpoint
 */
export interface IgnitionEndpoint {
    /**
     * The URL for the ignition endpoint.
     * @type {string}
     * @memberof IgnitionEndpoint
     */
    url?: string | null;
    /**
     * base64 encoded CA certficate to be used when contacting the URL via https.
     * @type {string}
     * @memberof IgnitionEndpoint
     */
    caCertificate?: string | null;
}
