/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostStaticNetworkConfig } from './host-static-network-config';
import { ImageType } from './image-type';
/**
 * 
 * @export
 * @interface ImageCreateParams
 */
export interface ImageCreateParams {
    /**
     * SSH public key for debugging the installation.
     * @type {string}
     * @memberof ImageCreateParams
     */
    sshPublicKey?: string;
    /**
     * 
     * @type {Array<HostStaticNetworkConfig>}
     * @memberof ImageCreateParams
     */
    staticNetworkConfig?: Array<HostStaticNetworkConfig>;
    /**
     * 
     * @type {ImageType}
     * @memberof ImageCreateParams
     */
    imageType?: ImageType;
}
