/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImportClusterParams
 */
export interface ImportClusterParams {
    /**
     * OpenShift cluster name.
     * @type {string}
     * @memberof ImportClusterParams
     */
    name: string;
    /**
     * The domain name used to reach the OpenShift cluster API.
     * @type {string}
     * @memberof ImportClusterParams
     */
    apiVipDnsname: string;
    /**
     * Version of the OpenShift cluster.
     * @type {string}
     * @memberof ImportClusterParams
     */
    openshiftVersion?: string;
    /**
     * The id of the OCP cluster, that hosts will be added to
     * @type {string}
     * @memberof ImportClusterParams
     */
    openshiftClusterId: string;
}
