/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostStaticNetworkConfig } from './host-static-network-config';
import { ImageType } from './image-type';
import { KernelArguments } from './kernel-arguments';
import { Proxy } from './proxy';
/**
 * 
 * @export
 * @interface InfraEnvUpdateParams
 */
export interface InfraEnvUpdateParams {
    /**
     * 
     * @type {Proxy}
     * @memberof InfraEnvUpdateParams
     */
    proxy?: Proxy;
    /**
     * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
     * @type {string}
     * @memberof InfraEnvUpdateParams
     */
    additionalNtpSources?: string | null;
    /**
     * SSH public key for debugging the installation.
     * @type {string}
     * @memberof InfraEnvUpdateParams
     */
    sshAuthorizedKey?: string | null;
    /**
     * The pull secret obtained from Red Hat OpenShift Cluster Manager at console.redhat.com/openshift/install/pull-secret.
     * @type {string}
     * @memberof InfraEnvUpdateParams
     */
    pullSecret?: string;
    /**
     * 
     * @type {Array<HostStaticNetworkConfig>}
     * @memberof InfraEnvUpdateParams
     */
    staticNetworkConfig?: Array<HostStaticNetworkConfig>;
    /**
     * 
     * @type {ImageType}
     * @memberof InfraEnvUpdateParams
     */
    imageType?: ImageType;
    /**
     * JSON formatted string containing the user overrides for the initial ignition config.
     * @type {string}
     * @memberof InfraEnvUpdateParams
     */
    ignitionConfigOverride?: string;
    /**
     * 
     * @type {KernelArguments}
     * @memberof InfraEnvUpdateParams
     */
    kernelArguments?: KernelArguments;
    /**
     * Allows users to change the additional_trust_bundle infra-env field
     * @type {string}
     * @memberof InfraEnvUpdateParams
     */
    additionalTrustBundle?: string | null;
}
