/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostStaticNetworkConfig } from './host-static-network-config';
import { ImageType } from './image-type';
import { KernelArguments } from './kernel-arguments';
import { Proxy } from './proxy';
/**
 * 
 * @export
 * @interface InfraEnvCreateParams
 */
export interface InfraEnvCreateParams {
    /**
     * Name of the infra-env.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    name: string;
    /**
     * 
     * @type {Proxy}
     * @memberof InfraEnvCreateParams
     */
    proxy?: Proxy;
    /**
     * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    additionalNtpSources?: string | null;
    /**
     * SSH public key for debugging the installation.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    sshAuthorizedKey?: string | null;
    /**
     * The pull secret obtained from Red Hat OpenShift Cluster Manager at console.redhat.com/openshift/install/pull-secret.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    pullSecret: string;
    /**
     * 
     * @type {Array<HostStaticNetworkConfig>}
     * @memberof InfraEnvCreateParams
     */
    staticNetworkConfig?: Array<HostStaticNetworkConfig>;
    /**
     * 
     * @type {ImageType}
     * @memberof InfraEnvCreateParams
     */
    imageType?: ImageType;
    /**
     * JSON formatted string containing the user overrides for the initial ignition config.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    ignitionConfigOverride?: string;
    /**
     * If set, all hosts that register will be associated with the specified cluster.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    clusterId?: string | null;
    /**
     * Version of the OpenShift cluster (used to infer the RHCOS version - temporary until generic logic implemented).
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    openshiftVersion?: string;
    /**
     * The CPU architecture of the image (x86_64/arm64/etc).
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    cpuArchitecture?: InfraEnvCreateParamsCpuArchitectureEnum;
    /**
     * 
     * @type {KernelArguments}
     * @memberof InfraEnvCreateParams
     */
    kernelArguments?: KernelArguments;
    /**
     * PEM-encoded X.509 certificate bundle. Hosts discovered by this infra-env will trust the certificates in this bundle. Clusters formed from the hosts discovered by this infra-env will also trust the certificates in this bundle.
     * @type {string}
     * @memberof InfraEnvCreateParams
     */
    additionalTrustBundle?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum InfraEnvCreateParamsCpuArchitectureEnum {
    X8664 = 'x86_64',
    Aarch64 = 'aarch64',
    Arm64 = 'arm64',
    Ppc64le = 'ppc64le',
    S390x = 's390x'
}

