/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InfraError
 */
export interface InfraError {
    /**
     * Numeric identifier of the error.
     * @type {number}
     * @memberof InfraError
     */
    code: number;
    /**
     * Human-readable description of the error.
     * @type {string}
     * @memberof InfraError
     */
    message: string;
}
