/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ip } from './ip';
import { VipVerification } from './vip-verification';
/**
 * The virtual IP used for cluster ingress traffic.
 * @export
 * @interface IngressVip
 */
export interface IngressVip {
    /**
     * The cluster that this VIP is associated with.
     * @type {string}
     * @memberof IngressVip
     */
    clusterId?: string;
    /**
     * 
     * @type {Ip}
     * @memberof IngressVip
     */
    ip?: Ip;
    /**
     * 
     * @type {VipVerification}
     * @memberof IngressVip
     */
    verification?: VipVerification;
}
