/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InstallerArgsParams
 */
export interface InstallerArgsParams {
    /**
     * List of additional arguments passed to coreos-installer
     * @type {Array<string>}
     * @memberof InstallerArgsParams
     */
    args?: Array<string>;
}
