/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostRole } from './host-role';
import { Proxy } from './proxy';
/**
 * 
 * @export
 * @interface InstallCmdRequest
 */
export interface InstallCmdRequest {
    /**
     * Cluster id
     * @type {string}
     * @memberof InstallCmdRequest
     */
    clusterId: string;
    /**
     * Infra env id
     * @type {string}
     * @memberof InstallCmdRequest
     */
    infraEnvId: string;
    /**
     * Host id
     * @type {string}
     * @memberof InstallCmdRequest
     */
    hostId: string;
    /**
     * 
     * @type {HostRole}
     * @memberof InstallCmdRequest
     */
    role: HostRole;
    /**
     * Boot device to write image on
     * @type {string}
     * @memberof InstallCmdRequest
     */
    bootDevice: string;
    /**
     * Assisted installer controller image
     * @type {string}
     * @memberof InstallCmdRequest
     */
    controllerImage: string;
    /**
     * Assisted installer image
     * @type {string}
     * @memberof InstallCmdRequest
     */
    installerImage: string;
    /**
     * Guaranteed availability of the installed cluster. 'Full' installs a Highly-Available cluster over multiple master nodes whereas 'None' installs a full cluster over one node. 
     * @type {string}
     * @memberof InstallCmdRequest
     */
    highAvailabilityMode?: InstallCmdRequestHighAvailabilityModeEnum;
    /**
     * 
     * @type {Proxy}
     * @memberof InstallCmdRequest
     */
    proxy?: Proxy;
    /**
     * Check CVO status if needed
     * @type {boolean}
     * @memberof InstallCmdRequest
     */
    checkCvo?: boolean;
    /**
     * List of disks to format
     * @type {Array<string>}
     * @memberof InstallCmdRequest
     */
    disksToFormat?: Array<string>;
    /**
     * Must-gather images to use
     * @type {string}
     * @memberof InstallCmdRequest
     */
    mustGatherImage?: string;
    /**
     * Machine config operator image
     * @type {string}
     * @memberof InstallCmdRequest
     */
    mcoImage?: string;
    /**
     * Version of the OpenShift cluster.
     * @type {string}
     * @memberof InstallCmdRequest
     */
    openshiftVersion?: string;
    /**
     * List of service ips
     * @type {Array<string>}
     * @memberof InstallCmdRequest
     */
    serviceIps?: Array<string>;
    /**
     * Core-os installer addtional args
     * @type {string}
     * @memberof InstallCmdRequest
     */
    installerArgs?: string;
    /**
     * Skip formatting installation disk
     * @type {boolean}
     * @memberof InstallCmdRequest
     */
    skipInstallationDiskCleanup?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum InstallCmdRequestHighAvailabilityModeEnum {
    Full = 'Full',
    None = 'None'
}

