/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Boot } from './boot';
import { Cpu } from './cpu';
import { Disk } from './disk';
import { Gpu } from './gpu';
import { Memory } from './memory';
import { ModelInterface } from './model-interface';
import { Route } from './route';
import { SystemVendor } from './system-vendor';
/**
 * 
 * @export
 * @interface Inventory
 */
export interface Inventory {
    /**
     * 
     * @type {string}
     * @memberof Inventory
     */
    hostname?: string;
    /**
     * 
     * @type {string}
     * @memberof Inventory
     */
    bmcAddress?: string;
    /**
     * 
     * @type {Array<ModelInterface>}
     * @memberof Inventory
     */
    interfaces?: Array<ModelInterface>;
    /**
     * 
     * @type {Array<Disk>}
     * @memberof Inventory
     */
    disks?: Array<Disk>;
    /**
     * 
     * @type {Boot}
     * @memberof Inventory
     */
    boot?: Boot;
    /**
     * 
     * @type {SystemVendor}
     * @memberof Inventory
     */
    systemVendor?: SystemVendor;
    /**
     * 
     * @type {string}
     * @memberof Inventory
     */
    bmcV6address?: string;
    /**
     * 
     * @type {Memory}
     * @memberof Inventory
     */
    memory?: Memory;
    /**
     * 
     * @type {Cpu}
     * @memberof Inventory
     */
    cpu?: Cpu;
    /**
     * 
     * @type {Array<Gpu>}
     * @memberof Inventory
     */
    gpus?: Array<Gpu>;
    /**
     * 
     * @type {Array<Route>}
     * @memberof Inventory
     */
    routes?: Array<Route>;
    /**
     * 
     * @type {string}
     * @memberof Inventory
     */
    tpmVersion?: InventoryTpmVersionEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum InventoryTpmVersionEnum {
    None = 'none',
    _12 = '1.2',
    _20 = '2.0'
}

