/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KernelArgument } from './kernel-argument';
/**
 * List of kernel arugment objects that define the operations and values to be applied.
 * @export
 * @interface KernelArguments
 */
export interface KernelArguments extends Array<KernelArgument> {
}
