/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface L2Connectivity
 */
export interface L2Connectivity {
    /**
     * 
     * @type {string}
     * @memberof L2Connectivity
     */
    outgoingNic?: string;
    /**
     * 
     * @type {string}
     * @memberof L2Connectivity
     */
    outgoingIpAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof L2Connectivity
     */
    remoteIpAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof L2Connectivity
     */
    remoteMac?: string;
    /**
     * 
     * @type {boolean}
     * @memberof L2Connectivity
     */
    successful?: boolean;
}
