/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface L3Connectivity
 */
export interface L3Connectivity {
    /**
     * 
     * @type {string}
     * @memberof L3Connectivity
     */
    outgoingNic?: string;
    /**
     * 
     * @type {string}
     * @memberof L3Connectivity
     */
    remoteIpAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof L3Connectivity
     */
    successful?: boolean;
    /**
     * Average round trip time in milliseconds.
     * @type {number}
     * @memberof L3Connectivity
     */
    averageRttMs?: number;
    /**
     * Percentage of packets lost during connectivity check.
     * @type {number}
     * @memberof L3Connectivity
     */
    packetLossPercentage?: number;
}
