/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MacInterfaceMapInner
 */
export interface MacInterfaceMapInner {
    /**
     * mac address present on the host
     * @type {string}
     * @memberof MacInterfaceMapInner
     */
    macAddress?: string;
    /**
     * nic name used in the yaml, which relates 1:1 to the mac address
     * @type {string}
     * @memberof MacInterfaceMapInner
     */
    logicalNicName?: string;
}
