/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Subnet } from './subnet';
/**
 * A network that all hosts belonging to the cluster should have an interface with IP address in. The VIPs (if exist) belong to this network.
 * @export
 * @interface MachineNetwork
 */
export interface MachineNetwork {
    /**
     * The cluster that this network is associated with.
     * @type {string}
     * @memberof MachineNetwork
     */
    clusterId?: string;
    /**
     * 
     * @type {Subnet}
     * @memberof MachineNetwork
     */
    cidr?: Subnet;
}
