/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ManagedDomain
 */
export interface ManagedDomain {
    /**
     * 
     * @type {string}
     * @memberof ManagedDomain
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedDomain
     */
    provider?: ManagedDomainProviderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ManagedDomainProviderEnum {
    Route53 = 'route53'
}

