/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Manifest
 */
export interface Manifest {
    /**
     * The folder that contains the files. Manifests can be placed in 'manifests' or 'openshift' directories.
     * @type {string}
     * @memberof Manifest
     */
    folder?: ManifestFolderEnum;
    /**
     * The file name prefaced by the folder that contains it.
     * @type {string}
     * @memberof Manifest
     */
    fileName?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ManifestFolderEnum {
    Manifests = 'manifests',
    Openshift = 'openshift'
}

