/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MemoryMethod } from './memory-method';
/**
 * 
 * @export
 * @interface Memory
 */
export interface Memory {
    /**
     * 
     * @type {number}
     * @memberof Memory
     */
    physicalBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof Memory
     */
    usableBytes?: number;
    /**
     * 
     * @type {MemoryMethod}
     * @memberof Memory
     */
    physicalBytesMethod?: MemoryMethod;
}
