/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModelInterface
 */
export interface ModelInterface {
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelInterface
     */
    ipv6Addresses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    vendor?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelInterface
     */
    hasCarrier?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    product?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelInterface
     */
    mtu?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelInterface
     */
    ipv4Addresses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    biosdevname?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    macAddress?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelInterface
     */
    flags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ModelInterface
     */
    speedMbps?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelInterface
     */
    type?: string;
}
