/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperatorStatus } from './operator-status';
import { OperatorType } from './operator-type';
/**
 * 
 * @export
 * @interface MonitoredOperator
 */
export interface MonitoredOperator {
    /**
     * The cluster that this operator is associated with.
     * @type {string}
     * @memberof MonitoredOperator
     */
    clusterId?: string;
    /**
     * Unique name of the operator.
     * @type {string}
     * @memberof MonitoredOperator
     */
    name?: string;
    /**
     * Operator version
     * @type {string}
     * @memberof MonitoredOperator
     */
    version?: string;
    /**
     * Namespace where to deploy an operator. Only some operators require a namespace.
     * @type {string}
     * @memberof MonitoredOperator
     */
    namespace?: string;
    /**
     * The name of the subscription of the operator.
     * @type {string}
     * @memberof MonitoredOperator
     */
    subscriptionName?: string;
    /**
     * 
     * @type {OperatorType}
     * @memberof MonitoredOperator
     */
    operatorType?: OperatorType;
    /**
     * Blob of operator-dependent parameters that are required for installation.
     * @type {string}
     * @memberof MonitoredOperator
     */
    properties?: string;
    /**
     * Positive number represents a timeout in seconds for the operator to be available.
     * @type {number}
     * @memberof MonitoredOperator
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {OperatorStatus}
     * @memberof MonitoredOperator
     */
    status?: OperatorStatus;
    /**
     * Detailed information about the operator state.
     * @type {string}
     * @memberof MonitoredOperator
     */
    statusInfo?: string;
    /**
     * Time at which the operator was last updated.
     * @type {Date}
     * @memberof MonitoredOperator
     */
    statusUpdatedAt?: Date;
}
