/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NextStepCmdRequest
 */
export interface NextStepCmdRequest {
    /**
     * Infra env id
     * @type {string}
     * @memberof NextStepCmdRequest
     */
    infraEnvId: string;
    /**
     * Host id
     * @type {string}
     * @memberof NextStepCmdRequest
     */
    hostId: string;
    /**
     * Agent image version
     * @type {string}
     * @memberof NextStepCmdRequest
     */
    agentVersion: string;
}
