/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NodeLabelParams
 */
export interface NodeLabelParams {
    /**
     * The key for the label's key-value pair.
     * @type {string}
     * @memberof NodeLabelParams
     */
    key: string;
    /**
     * The value for the label's key-value pair.
     * @type {string}
     * @memberof NodeLabelParams
     */
    value: string;
}
