/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NtpSynchronizationRequest
 */
export interface NtpSynchronizationRequest {
    /**
     * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
     * @type {string}
     * @memberof NtpSynchronizationRequest
     */
    ntpSource: string;
}
