/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SourceState } from './source-state';
/**
 * 
 * @export
 * @interface NtpSource
 */
export interface NtpSource {
    /**
     * NTP source name or IP.
     * @type {string}
     * @memberof NtpSource
     */
    sourceName?: string;
    /**
     * 
     * @type {SourceState}
     * @memberof NtpSource
     */
    sourceState?: SourceState;
}
