/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OpenshiftVersion
 */
export interface OpenshiftVersion {
    /**
     * Name of the version to be presented to the user.
     * @type {string}
     * @memberof OpenshiftVersion
     */
    displayName: string;
    /**
     * Level of support of the version.
     * @type {string}
     * @memberof OpenshiftVersion
     */
    supportLevel: OpenshiftVersionSupportLevelEnum;
    /**
     * Indication that the version is the recommended one.
     * @type {boolean}
     * @memberof OpenshiftVersion
     */
    _default?: boolean;
    /**
     * Available CPU architectures.
     * @type {Array<string>}
     * @memberof OpenshiftVersion
     */
    cpuArchitectures: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum OpenshiftVersionSupportLevelEnum {
    Beta = 'beta',
    Production = 'production',
    Maintenance = 'maintenance'
}

