/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperatorCreateParams
 */
export interface OperatorCreateParams {
    /**
     * 
     * @type {string}
     * @memberof OperatorCreateParams
     */
    name?: string;
    /**
     * Blob of operator-dependent parameters that are required for installation.
     * @type {string}
     * @memberof OperatorCreateParams
     */
    properties?: string;
}
