/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostTypeHardwareRequirementsWrapper } from './host-type-hardware-requirements-wrapper';
/**
 * 
 * @export
 * @interface OperatorHardwareRequirements
 */
export interface OperatorHardwareRequirements {
    /**
     * Unique name of the operator. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.
     * @type {string}
     * @memberof OperatorHardwareRequirements
     */
    operatorName?: string;
    /**
     * List of other operator unique names that are required to be installed. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.
     * @type {Array<string>}
     * @memberof OperatorHardwareRequirements
     */
    dependencies?: Array<string>;
    /**
     * 
     * @type {HostTypeHardwareRequirementsWrapper}
     * @memberof OperatorHardwareRequirements
     */
    requirements?: HostTypeHardwareRequirementsWrapper;
}
