/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperatorProperty
 */
export interface OperatorProperty {
    /**
     * Name of the property
     * @type {string}
     * @memberof OperatorProperty
     */
    name?: string;
    /**
     * Type of the property
     * @type {string}
     * @memberof OperatorProperty
     */
    dataType?: OperatorPropertyDataTypeEnum;
    /**
     * Indicates whether the property is reqired
     * @type {boolean}
     * @memberof OperatorProperty
     */
    mandatory?: boolean;
    /**
     * Values to select from
     * @type {Array<string>}
     * @memberof OperatorProperty
     */
    options?: Array<string>;
    /**
     * Description of a property
     * @type {string}
     * @memberof OperatorProperty
     */
    description?: string;
    /**
     * Default value for the property
     * @type {string}
     * @memberof OperatorProperty
     */
    defaultValue?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum OperatorPropertyDataTypeEnum {
    Boolean = 'boolean',
    String = 'string',
    Integer = 'integer',
    Float = 'float'
}

