/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
/**
 * 
 * @export
 * @interface OperatorHostRequirements
 */
export interface OperatorHostRequirements {
    /**
     * Name of the operator
     * @type {string}
     * @memberof OperatorHostRequirements
     */
    operatorName?: string;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof OperatorHostRequirements
     */
    requirements?: ClusterHostRequirementsDetails;
}
