/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperatorStatus } from './operator-status';
/**
 * 
 * @export
 * @interface OperatorMonitorReport
 */
export interface OperatorMonitorReport {
    /**
     * Unique name of the operator.
     * @type {string}
     * @memberof OperatorMonitorReport
     */
    name?: string;
    /**
     * operator version.
     * @type {string}
     * @memberof OperatorMonitorReport
     */
    version?: string;
    /**
     * 
     * @type {OperatorStatus}
     * @memberof OperatorMonitorReport
     */
    status?: OperatorStatus;
    /**
     * Detailed information about the operator state.
     * @type {string}
     * @memberof OperatorMonitorReport
     */
    statusInfo?: string;
}
