/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlatformType } from './platform-type';
/**
 * The configuration for the specific platform upon which to perform the installation.
 * @export
 * @interface Platform
 */
export interface Platform {
    /**
     * 
     * @type {PlatformType}
     * @memberof Platform
     */
    type: PlatformType;
    /**
     * Indicates if the underlying platform type is external.
     * @type {boolean}
     * @memberof Platform
     */
    isExternal?: boolean;
}
