/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HostTypeHardwareRequirementsWrapper } from './host-type-hardware-requirements-wrapper';
import { OperatorHardwareRequirements } from './operator-hardware-requirements';
/**
 * 
 * @export
 * @interface PreflightHardwareRequirements
 */
export interface PreflightHardwareRequirements {
    /**
     * Preflight operators hardware requirements
     * @type {Array<OperatorHardwareRequirements>}
     * @memberof PreflightHardwareRequirements
     */
    operators?: Array<OperatorHardwareRequirements>;
    /**
     * 
     * @type {HostTypeHardwareRequirementsWrapper}
     * @memberof PreflightHardwareRequirements
     */
    ocp?: HostTypeHardwareRequirementsWrapper;
}
