/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PresignedUrl
 */
export interface PresignedUrl {
    /**
     * Pre-signed URL for downloading the infra-env discovery image.
     * @type {string}
     * @memberof PresignedUrl
     */
    url: string;
    /**
     * Expiration time for the URL token.
     * @type {Date}
     * @memberof PresignedUrl
     */
    expiresAt?: Date;
}
