/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Proxy
 */
export interface Proxy {
    /**
     * A proxy URL to use for creating HTTP connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof Proxy
     */
    httpProxy?: string | null;
    /**
     * A proxy URL to use for creating HTTPS connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof Proxy
     */
    httpsProxy?: string | null;
    /**
     * An \"*\" or a comma-separated list of destination domain names, domains, IP addresses, or other network CIDRs to exclude from proxying.
     * @type {string}
     * @memberof Proxy
     */
    noProxy?: string | null;
}
