/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReleaseImage
 */
export interface ReleaseImage {
    /**
     * Version of the OpenShift cluster.
     * @type {string}
     * @memberof ReleaseImage
     */
    openshiftVersion: string;
    /**
     * (DEPRECATED) The CPU architecture of the image (x86_64/arm64/etc).
     * @type {string}
     * @memberof ReleaseImage
     */
    cpuArchitecture: ReleaseImageCpuArchitectureEnum;
    /**
     * List of CPU architectures provided by the image.
     * @type {Array<string>}
     * @memberof ReleaseImage
     */
    cpuArchitectures?: Array<string>;
    /**
     * The installation image of the OpenShift cluster.
     * @type {string}
     * @memberof ReleaseImage
     */
    url: string;
    /**
     * OCP version from the release metadata.
     * @type {string}
     * @memberof ReleaseImage
     */
    version: string;
    /**
     * Indication that the version is the recommended one.
     * @type {boolean}
     * @memberof ReleaseImage
     */
    _default?: boolean;
    /**
     * Level of support of the version.
     * @type {string}
     * @memberof ReleaseImage
     */
    supportLevel?: ReleaseImageSupportLevelEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReleaseImageCpuArchitectureEnum {
    X8664 = 'x86_64',
    Aarch64 = 'aarch64',
    Arm64 = 'arm64',
    Ppc64le = 'ppc64le',
    S390x = 's390x',
    Multi = 'multi'
}
/**
    * @export
    * @enum {string}
    */
export enum ReleaseImageSupportLevelEnum {
    Beta = 'beta',
    Production = 'production',
    Maintenance = 'maintenance'
}

