/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Route
 */
export interface Route {
    /**
     * Interface to which packets for this route will be sent
     * @type {string}
     * @memberof Route
     */
    _interface?: string;
    /**
     * Gateway address where the packets are sent
     * @type {string}
     * @memberof Route
     */
    gateway?: string;
    /**
     * The destination network or destination host
     * @type {string}
     * @memberof Route
     */
    destination?: string;
    /**
     * Defines whether this is an IPv4 (4) or IPv6 route (6)
     * @type {number}
     * @memberof Route
     */
    family?: number;
    /**
     * Route priority metric
     * @type {number}
     * @memberof Route
     */
    metric?: number;
}
