/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Subnet } from './subnet';
/**
 * IP address block for service IP blocks.
 * @export
 * @interface ServiceNetwork
 */
export interface ServiceNetwork {
    /**
     * A network to use for service IP addresses. If you need to access the services from an external network, configure load balancers and routers to manage the traffic.
     * @type {string}
     * @memberof ServiceNetwork
     */
    clusterId?: string;
    /**
     * 
     * @type {Subnet}
     * @memberof ServiceNetwork
     */
    cidr?: Subnet;
}
