/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StepType } from './step-type';
/**
 * 
 * @export
 * @interface Step
 */
export interface Step {
    /**
     * 
     * @type {StepType}
     * @memberof Step
     */
    stepType?: StepType;
    /**
     * 
     * @type {string}
     * @memberof Step
     */
    stepId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Step
     */
    args?: Array<string>;
}
