/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StepType } from './step-type';
/**
 * 
 * @export
 * @interface StepReply
 */
export interface StepReply {
    /**
     * 
     * @type {StepType}
     * @memberof StepReply
     */
    stepType?: StepType;
    /**
     * 
     * @type {string}
     * @memberof StepReply
     */
    stepId?: string;
    /**
     * 
     * @type {number}
     * @memberof StepReply
     */
    exitCode?: number;
    /**
     * 
     * @type {string}
     * @memberof StepReply
     */
    output?: string;
    /**
     * 
     * @type {string}
     * @memberof StepReply
     */
    error?: string;
}
