/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Step } from './step';
/**
 * 
 * @export
 * @interface Steps
 */
export interface Steps {
    /**
     * 
     * @type {number}
     * @memberof Steps
     */
    nextInstructionSeconds?: number;
    /**
     * What to do after finishing to run step instructions
     * @type {string}
     * @memberof Steps
     */
    postStepAction?: StepsPostStepActionEnum;
    /**
     * 
     * @type {Array<Step>}
     * @memberof Steps
     */
    instructions?: Array<Step>;
}

/**
    * @export
    * @enum {string}
    */
export enum StepsPostStepActionEnum {
    Exit = 'exit',
    Continue = 'continue'
}

