/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum StepType {
    ConnectivityCheck = 'connectivity-check',
    Execute = 'execute',
    Inventory = 'inventory',
    Install = 'install',
    FreeNetworkAddresses = 'free-network-addresses',
    DhcpLeaseAllocate = 'dhcp-lease-allocate',
    ApiVipConnectivityCheck = 'api-vip-connectivity-check',
    TangConnectivityCheck = 'tang-connectivity-check',
    NtpSynchronizer = 'ntp-synchronizer',
    InstallationDiskSpeedCheck = 'installation-disk-speed-check',
    ContainerImageAvailability = 'container-image-availability',
    DomainResolution = 'domain-resolution',
    StopInstallation = 'stop-installation',
    LogsGather = 'logs-gather',
    NextStepRunner = 'next-step-runner',
    UpgradeAgent = 'upgrade-agent',
    DownloadBootArtifacts = 'download-boot-artifacts',
    RebootForReclaim = 'reboot-for-reclaim',
    VerifyVips = 'verify-vips'
}

