/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupportLevel } from './support-level';
/**
 * Map of feature ID or CPU architecture alongside their support level
 * @export
 * @interface SupportLevels
 */
export interface SupportLevels extends null<String, SupportLevel> {
}
