/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SystemVendor
 */
export interface SystemVendor {
    /**
     * 
     * @type {string}
     * @memberof SystemVendor
     */
    serialNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemVendor
     */
    productName?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemVendor
     */
    manufacturer?: string;
    /**
     * Whether the machine appears to be a virtual machine or not
     * @type {boolean}
     * @memberof SystemVendor
     */
    virtual?: boolean;
}
