/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TangConnectivityResponseSignatures } from './tang-connectivity-response-signatures';
/**
 * 
 * @export
 * @interface TangConnectivityResponseTangServerResponse
 */
export interface TangConnectivityResponseTangServerResponse {
    /**
     * Tang URL.
     * @type {string}
     * @memberof TangConnectivityResponseTangServerResponse
     */
    tangUrl?: string;
    /**
     * Tang response payload.
     * @type {string}
     * @memberof TangConnectivityResponseTangServerResponse
     */
    payload?: string;
    /**
     * 
     * @type {Array<TangConnectivityResponseSignatures>}
     * @memberof TangConnectivityResponseTangServerResponse
     */
    signatures?: Array<TangConnectivityResponseSignatures>;
}
