/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TangConnectivityResponseTangServerResponse } from './tang-connectivity-response-tang-server-response';
/**
 * 
 * @export
 * @interface TangConnectivityResponse
 */
export interface TangConnectivityResponse {
    /**
     * Tang check result.
     * @type {boolean}
     * @memberof TangConnectivityResponse
     */
    isSuccess?: boolean;
    /**
     * 
     * @type {Array<TangConnectivityResponseTangServerResponse>}
     * @memberof TangConnectivityResponse
     */
    tangServerResponse?: Array<TangConnectivityResponseTangServerResponse>;
}
