/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TangConnectivityRequest
 */
export interface TangConnectivityRequest {
    /**
     * JSON-formatted string containing additional information regarding tang's configuration
     * @type {string}
     * @memberof TangConnectivityRequest
     */
    tangServers: string;
}
