/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateManifestParams
 */
export interface UpdateManifestParams {
    /**
     * The folder for the manifest to modify.
     * @type {string}
     * @memberof UpdateManifestParams
     */
    folder: UpdateManifestParamsFolderEnum;
    /**
     * The file name for the manifest to modify.
     * @type {string}
     * @memberof UpdateManifestParams
     */
    fileName: string;
    /**
     * The new folder for the manifest. Manifests can be placed in 'manifests' or 'openshift' directories.
     * @type {string}
     * @memberof UpdateManifestParams
     */
    updatedFolder?: UpdateManifestParamsUpdatedFolderEnum;
    /**
     * The new file name for the manifest.
     * @type {string}
     * @memberof UpdateManifestParams
     */
    updatedFileName?: string | null;
    /**
     * The new base64 encoded manifest content.
     * @type {string}
     * @memberof UpdateManifestParams
     */
    updatedContent?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateManifestParamsFolderEnum {
    Manifests = 'manifests',
    Openshift = 'openshift'
}
/**
    * @export
    * @enum {string}
    */
export enum UpdateManifestParamsUpdatedFolderEnum {
    Manifests = 'manifests',
    Openshift = 'openshift'
}

