/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * Unique idenftifier of the feature
     * @type {string}
     * @memberof Usage
     */
    id?: string;
    /**
     * name of the feature to track
     * @type {string}
     * @memberof Usage
     */
    name?: string;
    /**
     * additional properties of the feature
     * @type {{ [key: string]: any; }}
     * @memberof Usage
     */
    data?: { [key: string]: any; };
}
