/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiVip } from './api-vip';
import { ClusterNetwork } from './cluster-network';
import { DiskEncryption } from './disk-encryption';
import { IgnitionEndpoint } from './ignition-endpoint';
import { IngressVip } from './ingress-vip';
import { MachineNetwork } from './machine-network';
import { OperatorCreateParams } from './operator-create-params';
import { Platform } from './platform';
import { ServiceNetwork } from './service-network';
/**
 * 
 * @export
 * @interface V2ClusterUpdateParams
 */
export interface V2ClusterUpdateParams {
    /**
     * OpenShift cluster name.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    name?: string | null;
    /**
     * Base domain of the cluster. All DNS records must be sub-domains of this base and include the cluster name.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    baseDnsDomain?: string | null;
    /**
     * IP address block from which Pod IPs are allocated. This block must not overlap with existing physical networks. These IP addresses are used for the Pod network, and if you need to access the Pods from an external network, configure load balancers and routers to manage the traffic.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    clusterNetworkCidr?: string | null;
    /**
     * 
     * @type {Platform}
     * @memberof V2ClusterUpdateParams
     */
    platform?: Platform;
    /**
     * The subnet prefix length to assign to each individual node. For example, if clusterNetworkHostPrefix is set to 23, then each node is assigned a /23 subnet out of the given cidr (clusterNetworkCIDR), which allows for 510 (2^(32 - 23) - 2) pod IPs addresses. If you are required to provide access to nodes from an external network, configure load balancers and routers to manage the traffic.
     * @type {number}
     * @memberof V2ClusterUpdateParams
     */
    clusterNetworkHostPrefix?: number | null;
    /**
     * The IP address pool to use for service IP addresses. You can enter only one IP address pool. If you need to access the services from an external network, configure load balancers and routers to manage the traffic.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    serviceNetworkCidr?: string | null;
    /**
     * (DEPRECATED) The virtual IP used to reach the OpenShift cluster's API.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    apiVip?: string | null;
    /**
     * The virtual IPs used to reach the OpenShift cluster's API. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
     * @type {Array<ApiVip>}
     * @memberof V2ClusterUpdateParams
     */
    apiVips?: Array<ApiVip> | null;
    /**
     * (DEPRECATED) The virtual IP used for cluster ingress traffic.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    ingressVip?: string | null;
    /**
     * The virtual IPs used for cluster ingress traffic. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
     * @type {Array<IngressVip>}
     * @memberof V2ClusterUpdateParams
     */
    ingressVips?: Array<IngressVip> | null;
    /**
     * The domain name used to reach the OpenShift cluster API.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    apiVipDnsName?: string | null;
    /**
     * A CIDR that all hosts belonging to the cluster should have an interfaces with IP address that belongs to this CIDR. The api_vip belongs to this CIDR.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    machineNetworkCidr?: string | null;
    /**
     * The pull secret obtained from Red Hat OpenShift Cluster Manager at console.redhat.com/openshift/install/pull-secret.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    pullSecret?: string | null;
    /**
     * SSH public key for debugging OpenShift nodes.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    sshPublicKey?: string | null;
    /**
     * Indicate if virtual IP DHCP allocation mode is enabled.
     * @type {boolean}
     * @memberof V2ClusterUpdateParams
     */
    vipDhcpAllocation?: boolean | null;
    /**
     * A proxy URL to use for creating HTTP connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    httpProxy?: string | null;
    /**
     * A proxy URL to use for creating HTTPS connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\> 
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    httpsProxy?: string | null;
    /**
     * An \"*\" or a comma-separated list of destination domain names, domains, IP addresses, or other network CIDRs to exclude from proxying.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    noProxy?: string | null;
    /**
     * Indicate if the networking is managed by the user.
     * @type {boolean}
     * @memberof V2ClusterUpdateParams
     */
    userManagedNetworking?: boolean | null;
    /**
     * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    additionalNtpSource?: string | null;
    /**
     * List of OLM operators to be installed.
     * @type {Array<OperatorCreateParams>}
     * @memberof V2ClusterUpdateParams
     */
    olmOperators?: Array<OperatorCreateParams>;
    /**
     * Enable/disable hyperthreading on master nodes, worker nodes, or all nodes.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    hyperthreading?: V2ClusterUpdateParamsHyperthreadingEnum;
    /**
     * The desired network type used.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    networkType?: V2ClusterUpdateParamsNetworkTypeEnum;
    /**
     * Schedule workloads on masters
     * @type {boolean}
     * @memberof V2ClusterUpdateParams
     */
    schedulableMasters?: boolean;
    /**
     * Cluster networks that are associated with this cluster.
     * @type {Array<ClusterNetwork>}
     * @memberof V2ClusterUpdateParams
     */
    clusterNetworks?: Array<ClusterNetwork> | null;
    /**
     * Service networks that are associated with this cluster.
     * @type {Array<ServiceNetwork>}
     * @memberof V2ClusterUpdateParams
     */
    serviceNetworks?: Array<ServiceNetwork> | null;
    /**
     * Machine networks that are associated with this cluster.
     * @type {Array<MachineNetwork>}
     * @memberof V2ClusterUpdateParams
     */
    machineNetworks?: Array<MachineNetwork> | null;
    /**
     * 
     * @type {DiskEncryption}
     * @memberof V2ClusterUpdateParams
     */
    diskEncryption?: DiskEncryption;
    /**
     * 
     * @type {IgnitionEndpoint}
     * @memberof V2ClusterUpdateParams
     */
    ignitionEndpoint?: IgnitionEndpoint;
    /**
     * A comma-separated list of tags that are associated to the cluster.
     * @type {string}
     * @memberof V2ClusterUpdateParams
     */
    tags?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum V2ClusterUpdateParamsHyperthreadingEnum {
    Masters = 'masters',
    Workers = 'workers',
    All = 'all',
    None = 'none'
}
/**
    * @export
    * @enum {string}
    */
export enum V2ClusterUpdateParamsNetworkTypeEnum {
    OpenShiftSDN = 'OpenShiftSDN',
    OVNKubernetes = 'OVNKubernetes'
}

