/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ip } from './ip';
import { VipType } from './vip-type';
import { VipVerification } from './vip-verification';
/**
 * Single VIP verification result.
 * @export
 * @interface VerifiedVip
 */
export interface VerifiedVip {
    /**
     * 
     * @type {Ip}
     * @memberof VerifiedVip
     */
    vip?: Ip;
    /**
     * 
     * @type {VipType}
     * @memberof VerifiedVip
     */
    vipType?: VipType;
    /**
     * 
     * @type {VipVerification}
     * @memberof VerifiedVip
     */
    verification?: VipVerification;
}
