/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
/**
 * 
 * @export
 * @interface VersionedHostRequirements
 */
export interface VersionedHostRequirements {
    /**
     * Version of the component for which requirements are defined
     * @type {string}
     * @memberof VersionedHostRequirements
     */
    version?: string;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof VersionedHostRequirements
     */
    master?: ClusterHostRequirementsDetails;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof VersionedHostRequirements
     */
    worker?: ClusterHostRequirementsDetails;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof VersionedHostRequirements
     */
    sno?: ClusterHostRequirementsDetails;
    /**
     * 
     * @type {ClusterHostRequirementsDetails}
     * @memberof VersionedHostRequirements
     */
    edgeWorker?: ClusterHostRequirementsDetails;
}
