/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ListVersions } from '../models';
import { OpenshiftVersions } from '../models';
/**
 * VersionsApi - axios parameter creator
 * @export
 */
export const VersionsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * List of component versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2ListComponentVersions: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/component-versions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication userAuth required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('Authorization')
            : await configuration.apiKey;
        localVarHeaderParameter['Authorization'] = localVarApiKeyValue;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieves the list of OpenShift supported versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v2ListSupportedOpenshiftVersions: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/openshift-versions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication userAuth required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('Authorization')
            : await configuration.apiKey;
        localVarHeaderParameter['Authorization'] = localVarApiKeyValue;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * VersionsApi - functional programming interface
 * @export
 */
export const VersionsApiFp = function (configuration?: Configuration) {
  return {
    /**
     * List of component versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2ListComponentVersions(
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ListVersions>>> {
      const localVarAxiosArgs = await VersionsApiAxiosParamCreator(
        configuration,
      ).v2ListComponentVersions(options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Retrieves the list of OpenShift supported versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2ListSupportedOpenshiftVersions(
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<OpenshiftVersions>>
    > {
      const localVarAxiosArgs = await VersionsApiAxiosParamCreator(
        configuration,
      ).v2ListSupportedOpenshiftVersions(options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * VersionsApi - factory interface
 * @export
 */
export const VersionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * List of component versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2ListComponentVersions(
      options?: AxiosRequestConfig,
    ): Promise<AxiosResponse<ListVersions>> {
      return VersionsApiFp(configuration)
        .v2ListComponentVersions(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieves the list of OpenShift supported versions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v2ListSupportedOpenshiftVersions(
      options?: AxiosRequestConfig,
    ): Promise<AxiosResponse<OpenshiftVersions>> {
      return VersionsApiFp(configuration)
        .v2ListSupportedOpenshiftVersions(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * VersionsApi - object-oriented interface
 * @export
 * @class VersionsApi
 * @extends {BaseAPI}
 */
export class VersionsApi extends BaseAPI {
  /**
   * List of component versions.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VersionsApi
   */
  public async v2ListComponentVersions(
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<ListVersions>> {
    return VersionsApiFp(this.configuration)
      .v2ListComponentVersions(options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * Retrieves the list of OpenShift supported versions.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VersionsApi
   */
  public async v2ListSupportedOpenshiftVersions(
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<OpenshiftVersions>> {
    return VersionsApiFp(this.configuration)
      .v2ListSupportedOpenshiftVersions(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
