name: Push to master

on:
  push:
    branches:
      - master

env:
  QUAY_ORG: openshift-assisted
  QUAY_REPO: assisted-installer-ui

jobs:
  publish-assisted-ui:
    #    if: ${{ github.repository == 'openshift-assisted/assisted-ui-lib' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.QUAY_REPO }}
          tags: >
            latest latest-${{ github.sha }}
          labels: |
            openshift-assisted.github.actor=${{ github.actor }}
            openshift-assisted.github.run_id=${{ github.run_id }}
          build-args: |
            AIUI_APP_GIT_SHA=${{ github.sha }}
            AIUI_APP_VERSION=latest
          containerfiles: podman/app.Containerfile
          context: .
      - name: Push to Quay.io
        id: push
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: quay.io/${{ env.QUAY_ORG }}
          username: ${{ secrets.QUAY_OPENSHIFT_ASSISTED_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_OPENSHIFT_ASSISTED_ROBOT_PASSWORD }}
