name: Push to master or release branches

on:
  push:
    branches:
      - master
      - releases/*

env:
  QUAY_ORG: quay.io/openshift-assisted
  QUAY_REPO: assisted-installer-ui

jobs:
  publish-assisted-ui:
    #if: ${{ github.repository == 'openshift-assisted/assisted-ui-lib' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Define AIUI_APP_VERSION
        run: |
          echo "AIUI_APP_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF_NAME}" = "master" ]]; then
            echo "AIUI_APP_VERSION='latest'" >> $GITHUB_ENV
          fi
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.QUAY_REPO }}
          tags: >
            latest-${{ github.sha }} latest
          labels: |
            org.openshift-assisted.github.repository=${{ github.repository }}
            org.openshift-assisted.github.actor=${{ github.actor }}
            org.openshift-assisted.github.run_id=${{ github.run_id }}
            org.openshift-assisted.github.sha=${{ github.sha }}
            org.openshift-assisted.github.ref_name=${{ github.ref_name }}
          build-args: |
            AIUI_APP_VERSION=${{ env.AIUI_APP_VERSION }}
            AIUI_APP_GIT_SHA=${{ github.sha }}
            AIUI_APP_IMAGE_REPO=${{ env.QUAY_ORG }}/${{ env.QUAY_REPO }}
          containerfiles: podman/assisted-ui.Containerfile
          context: .
      - name: Push to Quay.io
        id: push
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.QUAY_ORG }}
          username: ${{ secrets.QUAY_OPENSHIFT_ASSISTED_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_OPENSHIFT_ASSISTED_ROBOT_PASSWORD }}
